# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\adminpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminLogin(object):
    def setupUi(self, AdminLogin):
        AdminLogin.setObjectName("AdminLogin")
        AdminLogin.resize(550, 410)
        AdminLogin.setMinimumSize(QtCore.QSize(550, 410))
        AdminLogin.setMaximumSize(QtCore.QSize(550, 410))
        AdminLogin.setStyleSheet("QSlider::groove:horizontal {height: 10px; margin: 0 0;}\n"
"QSlider::handle:horizontal {background-color: rgb(0,150,250); border: 1px; border-radius:3px; height: \n"
"40px; width: 40px; margin: 0 0;}\n"
"QSlider::handle:horizontal:hover {background-color: rgb(0,200,150); border: 1px; border-radius:3px; height: \n"
"    40px; width: 40px; margin: 0 0;}\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color:rgb(230,240,240);\n"
"border:none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(230,255,255);\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(200,255,255);\n"
"    border:none;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 10px;\n"
"border:1px solid black;\n"
"}\n"
"\n"
"#AdminLogin{\n"
"    background-color:rgb(255,255,255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AdminLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.text_username = QtWidgets.QLineEdit(self.centralwidget)
        self.text_username.setGeometry(QtCore.QRect(80, 120, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_username.setFont(font)
        self.text_username.setAlignment(QtCore.Qt.AlignCenter)
        self.text_username.setObjectName("text_username")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(200, 280, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.text_password = QtWidgets.QLineEdit(self.centralwidget)
        self.text_password.setGeometry(QtCore.QRect(80, 200, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_password.setFont(font)
        self.text_password.setInputMask("")
        self.text_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_password.setAlignment(QtCore.Qt.AlignCenter)
        self.text_password.setObjectName("text_password")
        AdminLogin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminLogin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 22))
        self.menubar.setObjectName("menubar")
        AdminLogin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminLogin)
        self.statusbar.setObjectName("statusbar")
        AdminLogin.setStatusBar(self.statusbar)

        self.retranslateUi(AdminLogin)
        QtCore.QMetaObject.connectSlotsByName(AdminLogin)

    def retranslateUi(self, AdminLogin):
        _translate = QtCore.QCoreApplication.translate
        AdminLogin.setWindowTitle(_translate("AdminLogin", "Admin Login"))
        self.text_username.setPlaceholderText(_translate("AdminLogin", "Username"))
        self.btn_login.setText(_translate("AdminLogin", "Login"))
        self.label.setText(_translate("AdminLogin", "Admin Login"))
        self.text_password.setPlaceholderText(_translate("AdminLogin", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminLogin = QtWidgets.QMainWindow()
    ui = Ui_AdminLogin()
    ui.setupUi(AdminLogin)
    AdminLogin.show()
    sys.exit(app.exec_())
